version: '3.0'

services:
  grafana:
    container_name: 'grafana-explore-traces-e2e'
    build:
      context: ../.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-latest}
    ports:
      - 3001:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/grafana-explore-traces-e2e
      - ../provisioning:/etc/grafana/provisioning

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # tempo

  # generates uninteresting traces, but is useful for testing
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:latest
    environment:
      - ENDPOINT=tempo:4317
    restart: always
    depends_on:
      - tempo
