apiVersion: 1

datasources:
  - name: gdev-testdata
    isDefault: false
    type: testdata
  - name: gdev-tempo
    type: tempo
    uid: gdev-tempo
    access: proxy
    url: http://host.docker.internal:3200