name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    uses: grafana/explore-traces/.github/workflows/build.yml@main
