name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    uses: grafana/exploretraces-app/.github/workflows/build.yml@main
