name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call shared build action
        uses: ./.github/actions/build
      - name: Unit tests
        run: yarn test:ci
