name: Release main to GCS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: # Don't run the workflow if only .github/** or docs/** files have been changed
      - '.github/**'
      - 'docs/**'

jobs:
  build:
    uses: grafana/explore-traces/.github/workflows/build.yml@main
  release-and-upload:
    runs-on: ubuntu-latest
    steps:
      - id: 'upload-to-gcs'
        name: 'Upload assets to main'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: ./
          destination: 'integration-artifacts/grafana-exploretraces-app/'
          glob: ${{ jobs.build.outputs.archive }}
          parent: false