name: Build and release main to GCS

on:
  push:
    branches:
      - main
    paths-ignore: # Don't run the workflow if only docs files have been changed
      - 'docs/**'
      - '**.md'

jobs:
  build:
    uses: grafana/explore-traces/.github/workflows/build.yml@main
  upload:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - id: 'upload-to-gcs'
        name: 'Upload assets to main'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: ./grafana-exploretraces-app-main.zip
          destination: 'integration-artifacts/grafana-exploretraces-app/'
          parent: false