name: Build and release main to GCS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: # Don't run the workflow if only docs files have been changed
      - 'docs/**'
      - '**.md'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  upload:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: grafana-exploretraces-app
      - id: 'upload-to-gcs'
        name: 'Upload assets to main'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: ./grafana-exploretraces-app-main.zip
          destination: 'integration-artifacts/grafana-exploretraces-app/'
          parent: false