name: Build and release main to GCS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: # Don't run the workflow if only docs files have been changed
      - 'docs/**'
      - '**.md'

jobs:
  build:
    uses: ./.github/workflows/build.yml
  upload:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download zip
        uses: actions/download-artifact@v4
        with:
          name: grafana-exploretraces-app-main.zip
      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          common_secrets: |
            GCP_UPLOAD_ARTIFACTS_KEY=grafana/integration-artifacts-uploader-service-account:'credentials.json'
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ env.GCP_UPLOAD_ARTIFACTS_KEY }}
      - id: 'upload-to-gcs'
        name: 'Upload assets to main'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: ./grafana-exploretraces-app-main.zip
          destination: 'integration-artifacts/grafana-exploretraces-app/'
          parent: false